default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: <%= ENV["BASIC_AUTH_USER"] %>
  password: <%= ENV["BASIC_AUTH_PASSWORD"] %>
  host: localhost
  database: furima_38631_development

test:
  <<: *default
  adapter: mysql2
  username: <%= ENV["BASIC_AUTH_USER"] %>
  password: <%= ENV["BASIC_AUTH_PASSWORD"] %>
  host: localhost
  database: furima_38631_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>