default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: "admin"
  password: "2222"
  host: localhost
  database: furima_38631_development

test:
  <<: *default
  adapter: mysql2
  username: "admin"
  password: "2222"
  host: localhost
  database: furima_38631_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>

amazon:
 service: S3
 region: ap-northeast-1
 bucket: furima38631
 access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
 secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>